// GenUI Registry
// Auto-generated by GenUIService. Do not edit manually.
// This file exports all autonomous components for the Dashboard to consume.

export { AICPAJulieWidget } from "./AICPAJulieWidget";
export { BudgetDashboard } from "./BudgetDashboard";
export { FinalEternalVictoryWidget } from "./FinalEternalVictoryWidget";
export { GenesisWidget } from "./GenesisWidget";
export { JulieCPAWidget } from "./JulieCPAWidget";
export { JuliePrediction } from "./JuliePrediction";
export { JulieSuggestions } from "./JulieSuggestions";
export { KingdomChronicleTimeline } from "./KingdomChronicleTimeline";
export { SandboxCanvas } from "./SandboxCanvas";
export { SSOTMonitor } from "./SSOTMonitor";
export { TrinityHarmonyWidget } from "./TrinityHarmonyWidget";

// Phase 13: AICPA Agent Army Integration
export { AICPAControlPanel } from "../aicpa/AICPAControlPanel";
export { RothLadderSimulator } from "../aicpa/RothLadderSimulator";
export { TaxSimulationWidget } from "../aicpa/TaxSimulationWidget";

// Phase 14: Prophet Prediction
export { BudgetPredictionWidget } from "../aicpa/BudgetPredictionWidget";
export { default as FuturisticDashboard } from "./FuturisticDashboard";
export { default as KingdomMessageBoard } from "./KingdomMessageBoard";

